import type { Category } from "@/lib/platforms/categories";
import type { Listing, OrganizationRecord, RevocationReason } from "@/types";

/**
 * The demo world. Everything here is fictional — no real people, companies
 * or platforms.
 *
 * Two rules keep the demo legible:
 *
 * 1. Every person and organisation carries a plain-English `label` that is
 *    always rendered in brackets after the name, e.g.
 *    "NewHost23 (brand-new host who has never completed a booking)".
 *    Never a bare role word like "new host" — the bracket must say what that
 *    means.
 * 2. Between them the cast covers every case a presenter might be asked
 *    about: 0%, 10%, 50%, 100%, no history at all, a single data point,
 *    revoked by the issuer, revoked by the holder, stale records, high
 *    dispute rates, businesses rather than people, and both sides of the
 *    same transaction.
 */

type Tone = OrganizationRecord["tone"];

export interface CastCredential {
  issuer: string;
  type: string;
  values: Record<string, number>;
  daysAgo: number;
  category?: Category;
  revokedDaysAgo?: number;
  /** Who pulled the credential. Issuers correct records; holders withdraw them. */
  revokedBy?: "issuer" | "holder";
  revocationReason?: RevocationReason;
}

export interface CastPerson {
  id: string;
  name: string;
  /** Shown in brackets everywhere, and it must explain itself in full. */
  label: string;
  /** Which demo case this person illustrates, for the presenter's own notes. */
  scenario: string;
  tone: Tone;
  seed: string;
  published: string[];
  credentials: CastCredential[];
}

const cust = (successful: number, total: number, cancellations: number, noShows: number, paid: number, disputes = 0) => ({
  successful_transactions: successful,
  bookings_total: total,
  cancellations,
  no_shows: noShows,
  payments_completed: paid,
  disputes,
});

const prov = (completed: number, accepted: number, cancellations: number, accurate: number, disputes = 0) => ({
  completed_bookings: completed,
  bookings_accepted: accepted,
  host_cancellations: cancellations,
  accurate_listings: accurate,
  disputes,
});

const PUBLIC_PROVIDER = ["hosting_summary", "verified_credentials"];
const PUBLIC_CUSTOMER = ["booking_reliability", "verified_credentials"];
const PUBLIC_BOTH = ["hosting_summary", "booking_reliability", "seller_completion", "verified_credentials"];

// ── Organisations ───────────────────────────────────────────────────────────

/**
 * `description` is what the organisation does; `label` is the one-line gloss
 * shown in brackets next to its name, explaining its role in Trustline terms.
 */
export const ORGS: Omit<OrganizationRecord, "issuerPublicKey" | "issuerKeySealed">[] = [
  {
    id: "org_marketplace_a",
    name: "Marketplace A",
    shortName: "Marketplace A",
    description: "General goods and services marketplace",
    label: "issuer — a marketplace that vouches for its users by signing credentials",
    category: "marketplace",
    roles: ["issuer"],
    registered: true,
    allowedCredentialTypes: ["MARKETPLACE_REPUTATION", "SUCCESSFUL_TRANSACTION_COUNT"],
    allowedPurposes: [],
    historical: { issued: 1283, revoked: 83 },
    monogram: "A",
    tone: "emerald",
  },
  {
    id: "org_marketplace_b",
    name: "Marketplace B",
    shortName: "Marketplace B",
    description: "Peer-to-peer marketplace",
    label: "verifier — a marketplace that asks for proof before letting someone trade",
    category: "marketplace",
    roles: ["verifier"],
    registered: true,
    allowedCredentialTypes: [],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 0, revoked: 0 },
    monogram: "B",
    tone: "slate",
  },
  {
    id: "org_onecity",
    name: "OneCity",
    shortName: "OneCity",
    description: "The demo marketplace where every service in this app is booked",
    label: "issuer and verifier — the marketplace you book on inside this demo",
    category: "booking",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_OUTCOME", "PROVIDER_OUTCOME"],
    allowedPurposes: ["buyer_verification", "seller_verification", "guest_verification", "host_verification"],
    historical: { issued: 0, revoked: 0 },
    monogram: "O",
    tone: "rose",
  },
  {
    id: "org_hotel_platform",
    name: "Hotel Platform",
    shortName: "Hotel Platform",
    description: "Hotel and homestay booking platform",
    label: "issuer — a booking site that signs credentials about guests and hosts",
    category: "hospitality",
    roles: ["issuer"],
    registered: true,
    allowedCredentialTypes: ["GUEST_STAY_RECORD", "COMPLETED_STAY_COUNT", "HOSTING_RECORD"],
    allowedPurposes: [],
    historical: { issued: 5410, revoked: 212 },
    monogram: "H",
    tone: "amber",
  },
  {
    id: "org_work_platform",
    name: "Work Platform",
    shortName: "Work Platform",
    description: "Freelance work marketplace",
    label: "issuer — a freelance site that signs credentials about delivered projects",
    category: "work",
    roles: ["issuer"],
    registered: true,
    allowedCredentialTypes: ["FREELANCE_RECORD", "COMPLETED_PROJECT_COUNT"],
    allowedPurposes: [],
    historical: { issued: 912, revoked: 31 },
    monogram: "W",
    tone: "emerald",
  },
  {
    id: "org_ride_platform",
    name: "Ride Platform",
    shortName: "Ride Platform",
    description: "Ride booking platform",
    label: "issuer — a cab app that signs credentials about passengers",
    category: "mobility",
    roles: ["issuer"],
    registered: true,
    allowedCredentialTypes: ["RIDER_RECORD"],
    allowedPurposes: [],
    historical: { issued: 2240, revoked: 140 },
    monogram: "R",
    tone: "rose",
  },
  {
    id: "org_citystay",
    name: "CityStay",
    shortName: "CityStay",
    description: "Home-rental platform for homestays and apartments",
    label: "issuer — a home-rental site; it is the one that revokes a record in this demo",
    category: "stays",
    roles: ["issuer"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: [],
    historical: { issued: 3890, revoked: 164 },
    monogram: "C",
    tone: "sky",
  },
  {
    id: "org_tripnest",
    name: "TripNest",
    shortName: "TripNest",
    description: "Hotel booking platform",
    label: "issuer and verifier — a hotel site that both signs records and asks for proof",
    category: "hotels",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["guest_verification", "buyer_verification", "host_verification", "seller_verification"],
    historical: { issued: 7120, revoked: 301 },
    monogram: "T",
    tone: "indigo",
  },
  {
    id: "org_goride",
    name: "GoRide",
    shortName: "GoRide",
    description: "City rides and outstation travel",
    label: "issuer and verifier — a ride app covering drivers and passengers",
    category: "rides",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 15400, revoked: 512 },
    monogram: "G",
    tone: "amber",
  },
  {
    id: "org_drivenow",
    name: "DriveNow",
    shortName: "DriveNow",
    description: "Self-drive car rental",
    label: "issuer and verifier — a car-rental platform covering owners and renters",
    category: "car_rental",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 2210, revoked: 97 },
    monogram: "D",
    tone: "slate",
  },
  {
    id: "org_pedalpoint",
    name: "PedalPoint",
    shortName: "PedalPoint",
    description: "Bike and scooter rental",
    label: "issuer — a two-wheeler rental platform",
    category: "bikes",
    roles: ["issuer"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: [],
    historical: { issued: 6400, revoked: 180 },
    monogram: "P",
    tone: "emerald",
  },
  {
    id: "org_skyfare",
    name: "SkyFare",
    shortName: "SkyFare",
    description: "Flight booking and travel agency",
    label: "issuer and verifier — an airline ticketing platform",
    category: "flights",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 42800, revoked: 1120 },
    monogram: "S",
    tone: "sky",
  },
  {
    id: "org_wanderlocal",
    name: "WanderLocal",
    shortName: "WanderLocal",
    description: "Guided tours, treks and day experiences",
    label: "issuer and verifier — an experiences platform covering guides and travellers",
    category: "experiences",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 2900, revoked: 76 },
    monogram: "W",
    tone: "amber",
  },
  {
    id: "org_freshcart",
    name: "FreshCart",
    shortName: "FreshCart",
    description: "Grocery delivery",
    label: "issuer and verifier — a grocery platform covering stores and shoppers",
    category: "groceries",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 18200, revoked: 640 },
    monogram: "F",
    tone: "emerald",
  },
  {
    id: "org_tablebook",
    name: "TableBook",
    shortName: "TableBook",
    description: "Restaurant reservations",
    label: "issuer and verifier — a reservations platform covering restaurants and diners",
    category: "dining",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification", "guest_verification"],
    historical: { issued: 9300, revoked: 205 },
    monogram: "T",
    tone: "rose",
  },
  {
    id: "org_devhire",
    name: "DevHire",
    shortName: "DevHire",
    description: "IT project marketplace for freelancers and clients",
    label: "issuer and verifier — an IT-work marketplace covering freelancers and clients",
    category: "it_projects",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification", "freelancer_verification"],
    historical: { issued: 1480, revoked: 58 },
    monogram: "D",
    tone: "indigo",
  },
  {
    id: "org_learnloop",
    name: "LearnLoop",
    shortName: "LearnLoop",
    description: "Tutoring and small-batch classes",
    label: "issuer and verifier — a tutoring platform covering tutors and students",
    category: "tutoring",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 5600, revoked: 143 },
    monogram: "L",
    tone: "indigo",
  },
  {
    id: "org_fixitnow",
    name: "FixItNow",
    shortName: "FixItNow",
    description: "Home repair, cleaning and maintenance visits",
    label: "issuer and verifier — a home-services platform covering tradespeople and homeowners",
    category: "home_services",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 11400, revoked: 388 },
    monogram: "F",
    tone: "amber",
  },
  {
    id: "org_glowbar",
    name: "GlowBar",
    shortName: "GlowBar",
    description: "Salon, spa and wellness appointments",
    label: "issuer and verifier — a salon booking platform covering salons and clients",
    category: "beauty",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 7700, revoked: 164 },
    monogram: "G",
    tone: "rose",
  },
  {
    id: "org_medislot",
    name: "MediSlot",
    shortName: "MediSlot",
    description: "Clinic appointment booking — attendance only, never health data",
    label: "issuer — a clinic booking platform; it records attendance, never anything medical",
    category: "healthcare",
    roles: ["issuer"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: [],
    historical: { issued: 24100, revoked: 502 },
    monogram: "M",
    tone: "sky",
  },
  {
    id: "org_pawpals",
    name: "PawPals",
    shortName: "PawPals",
    description: "Pet boarding, walking and grooming",
    label: "issuer and verifier — a pet-care platform covering sitters and pet owners",
    category: "pet_care",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 3300, revoked: 88 },
    monogram: "P",
    tone: "emerald",
  },
  {
    id: "org_parcelpath",
    name: "ParcelPath",
    shortName: "ParcelPath",
    description: "Courier and last-mile delivery",
    label: "issuer and verifier — a courier network covering carriers and senders",
    category: "courier",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 31200, revoked: 910 },
    monogram: "P",
    tone: "slate",
  },
  {
    id: "org_gearvault",
    name: "GearVault",
    shortName: "GearVault",
    description: "Camera, tool and equipment rental",
    label: "issuer — an equipment rental platform covering owners and renters",
    category: "equipment",
    roles: ["issuer"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: [],
    historical: { issued: 1900, revoked: 61 },
    monogram: "G",
    tone: "slate",
  },
  {
    id: "org_deskhub",
    name: "DeskHub",
    shortName: "DeskHub",
    description: "Coworking desks and meeting rooms",
    label: "issuer and verifier — a coworking platform covering spaces and members",
    category: "coworking",
    roles: ["issuer", "verifier"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 4800, revoked: 120 },
    monogram: "D",
    tone: "indigo",
  },
  {
    id: "org_venuely",
    name: "Venuely",
    shortName: "Venuely",
    description: "Event halls, studios and venues",
    label: "issuer — an event-venue platform covering venues and organisers",
    category: "events",
    roles: ["issuer"],
    registered: true,
    allowedCredentialTypes: ["CUSTOMER_RECORD", "PROVIDER_RECORD"],
    allowedPurposes: [],
    historical: { issued: 2100, revoked: 74 },
    monogram: "V",
    tone: "amber",
  },
  {
    id: "org_lendfast",
    name: "LendFast",
    shortName: "LendFast",
    description: "Short-term lending app",
    label: "verifier — registered, but only for buyer checks; anything else is blocked by policy",
    category: "marketplace",
    roles: ["verifier"],
    registered: true,
    allowedCredentialTypes: [],
    allowedPurposes: ["buyer_verification"],
    historical: { issued: 0, revoked: 0 },
    monogram: "L",
    tone: "rose",
  },
  {
    id: "org_datascrape",
    name: "DataScrape Partners",
    shortName: "DataScrape",
    description: "Unverified data broker",
    label: "verifier — NOT registered with Trustline, so every request it makes is refused",
    category: "marketplace",
    roles: ["verifier"],
    registered: false,
    allowedCredentialTypes: [],
    allowedPurposes: ["buyer_verification", "seller_verification"],
    historical: { issued: 0, revoked: 0 },
    monogram: "?",
    tone: "slate",
  },
];

export const orgLabel = (id: string) => ORGS.find((o) => o.id === id)?.label;

// ── People ──────────────────────────────────────────────────────────────────

export const PEOPLE: CastPerson[] = [
  // ── The main holder ──────────────────────────────────────────────────────
  {
    id: "usr_vineet",
    name: "Vineet",
    label: "the main demo holder — 47 successful transactions, with credentials from four different platforms",
    scenario: "Excellent record across 4 platforms, including one credential the issuer later revoked",
    tone: "indigo",
    seed: "trustline-demo-holder:usr_vineet:61881",
    published: ["booking_reliability", "seller_completion", "verified_credentials"],
    credentials: [
      {
        issuer: "org_ride_platform",
        type: "RIDER_RECORD",
        values: { completed_rides: 31, rides_booked: 33, no_shows: 2 },
        daysAgo: 64,
        revokedDaysAgo: 9,
      },
      {
        issuer: "org_work_platform",
        type: "FREELANCE_RECORD",
        values: { completed_projects: 12, projects_accepted: 12, positive_outcomes: 12, cancellations: 0, disputes: 0 },
        daysAgo: 12,
      },
      {
        issuer: "org_marketplace_a",
        type: "MARKETPLACE_REPUTATION",
        values: {
          successful_transactions: 47,
          bookings_total: 52,
          cancellations: 3,
          no_shows: 2,
          payments_completed: 47,
          disputes: 0,
          seller_orders_accepted: 38,
          seller_orders_completed: 37,
          seller_cancellations: 1,
          seller_positive_outcomes: 36,
          seller_disputes: 1,
        },
        daysAgo: 45,
      },
      {
        issuer: "org_hotel_platform",
        type: "GUEST_STAY_RECORD",
        values: { completed_stays: 8, stays_booked: 8, cancellations: 0, no_shows: 0 },
        daysAgo: 44,
      },
    ],
  },

  // ── Stays: hosts ─────────────────────────────────────────────────────────
  {
    id: "usr_arjun",
    name: "Arjun",
    label: "host who rents out his Indiranagar flat — 124 of his 126 bookings were completed",
    scenario: "Excellent host whose record was earned on a different platform and still counts here",
    tone: "amber",
    seed: "trustline-demo-holder:usr_arjun:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_hotel_platform", type: "HOSTING_RECORD", values: prov(124, 126, 2, 122, 0), daysAgo: 300 }],
  },
  {
    id: "usr_meera",
    name: "Meera",
    label: "host with a shorter but spotless record — 62 of 63 bookings completed",
    scenario: "Solid host with a smaller history: good numbers from a modest sample",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_meera:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_hotel_platform", type: "HOSTING_RECORD", values: prov(62, 63, 1, 61, 0), daysAgo: 200 }],
  },
  {
    id: "usr_kabir",
    name: "Kabir",
    label: "host with lots of bookings but complaints on 18 of them — high dispute rate",
    scenario: "Good completion numbers hide a Moderate/High dispute rate — volume is not the whole story",
    tone: "sky",
    seed: "trustline-demo-holder:usr_kabir:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_citystay", type: "PROVIDER_RECORD", category: "stays", values: prov(198, 216, 6, 170, 18), daysAgo: 500 }],
  },
  {
    id: "usr_newhost23",
    name: "NewHost23",
    label: "brand-new host who has never completed a booking, so there is nothing to verify",
    scenario: "Zero history: Trustline says 'no verified history' without accusing anyone of anything",
    tone: "slate",
    seed: "trustline-demo-holder:usr_newhost23:0",
    published: PUBLIC_PROVIDER,
    credentials: [],
  },
  {
    id: "usr_ishita",
    name: "Ishita",
    label: "host who joined last month — 2 of 2 bookings completed, too little history to mean much",
    scenario: "100% from a sample of two: the UI flags limited history rather than showing a perfect score",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_ishita:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_citystay", type: "PROVIDER_RECORD", category: "stays", values: prov(2, 2, 0, 2, 0), daysAgo: 24 }],
  },
  {
    id: "usr_devansh",
    name: "Devansh",
    label: "host who cancels exactly half of what he accepts — 20 of 40 bookings called off",
    scenario: "The 50% case, sitting right between the good and the bad providers",
    tone: "amber",
    seed: "trustline-demo-holder:usr_devansh:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_citystay", type: "PROVIDER_RECORD", category: "stays", values: prov(20, 40, 20, 19, 5), daysAgo: 130 }],
  },
  {
    id: "usr_quickstays",
    name: "QuickStays99",
    label: "host whose record CityStay revoked after a policy review — proofs from it now fail",
    scenario: "Revoked by the issuer: the credential still exists but the ledger marks it dead",
    tone: "rose",
    seed: "trustline-demo-holder:usr_quickstays:0",
    published: PUBLIC_PROVIDER,
    credentials: [
      {
        issuer: "org_citystay",
        type: "PROVIDER_RECORD",
        category: "stays",
        values: prov(40, 52, 12, 28, 9),
        daysAgo: 120,
        revokedDaysAgo: 5,
        revokedBy: "issuer",
        revocationReason: "PLATFORM_POLICY",
      },
    ],
  },

  // ── Hotels ───────────────────────────────────────────────────────────────
  {
    id: "usr_lakeview",
    name: "Lakeview Residency",
    label: "a hotel business rather than a person — 2,140 of 2,200 bookings honoured",
    scenario: "Companies hold Trustlines too, with exactly the same privacy guarantees",
    tone: "indigo",
    seed: "trustline-demo-holder:usr_lakeview:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_tripnest", type: "PROVIDER_RECORD", category: "hotels", values: prov(2140, 2200, 40, 2050, 30), daysAgo: 700 }],
  },
  {
    id: "usr_bluepalm",
    name: "Blue Palm Inn",
    label: "budget hotel that honours about 8 of every 10 bookings it takes",
    scenario: "A mid-range provider: passes a 75% threshold, fails a 95% one",
    tone: "sky",
    seed: "trustline-demo-holder:usr_bluepalm:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_tripnest", type: "PROVIDER_RECORD", category: "hotels", values: prov(640, 800, 130, 590, 46), daysAgo: 330 }],
  },

  // ── Flights ──────────────────────────────────────────────────────────────
  {
    id: "usr_skybird",
    name: "SkyBird Airways",
    label: "airline that flew 18,900 of the 19,200 seats it sold",
    scenario: "Very large sample — the range proof is the same size no matter how big the number",
    tone: "sky",
    seed: "trustline-demo-holder:usr_skybird:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_skyfare", type: "PROVIDER_RECORD", category: "flights", values: prov(18900, 19200, 210, 18600, 240), daysAgo: 620 }],
  },
  {
    id: "usr_fareloop",
    name: "FareLoop Travel",
    label: "ticket agent that cancelled 1 in 4 of the bookings it took last year",
    scenario: "75% provider: useful for showing a threshold that just barely fails",
    tone: "rose",
    seed: "trustline-demo-holder:usr_fareloop:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_skyfare", type: "PROVIDER_RECORD", category: "flights", values: prov(900, 1200, 300, 840, 90), daysAgo: 210 }],
  },

  // ── Tours and experiences ────────────────────────────────────────────────
  {
    id: "usr_tenzin",
    name: "Tenzin",
    label: "trek guide who has run every one of his 86 tours as promised",
    scenario: "A clean 100% with a large enough sample to actually mean something",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_tenzin:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_wanderlocal", type: "PROVIDER_RECORD", category: "experiences", values: prov(86, 86, 0, 86, 0), daysAgo: 280 }],
  },
  {
    id: "usr_ritika",
    name: "Ritika",
    label: "heritage-walk guide who calls off tours when too few people book — 30 of 50 ran",
    scenario: "60% completion with an innocent explanation: Trustline shows behaviour, not motive",
    tone: "amber",
    seed: "trustline-demo-holder:usr_ritika:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_wanderlocal", type: "PROVIDER_RECORD", category: "experiences", values: prov(30, 50, 20, 30, 2), daysAgo: 150 }],
  },

  // ── Rides ────────────────────────────────────────────────────────────────
  {
    id: "usr_suresh",
    name: "Suresh",
    label: "cab driver with 900 rides behind him and a 90% completion rate",
    scenario: "Decent but not perfect: passes at 90%, fails at 95%",
    tone: "slate",
    seed: "trustline-demo-holder:usr_suresh:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_goride", type: "PROVIDER_RECORD", category: "rides", values: prov(812, 900, 70, 800, 9), daysAgo: 400 }],
  },
  {
    id: "usr_manoj",
    name: "Manoj",
    label: "driver who signed up six days ago — 3 rides, all completed, too few to judge",
    scenario: "A perfect percentage from three data points, flagged as limited history",
    tone: "sky",
    seed: "trustline-demo-holder:usr_manoj:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_goride", type: "PROVIDER_RECORD", category: "rides", values: prov(3, 3, 0, 3, 0), daysAgo: 6 }],
  },
  {
    id: "usr_imran",
    name: "Imran",
    label: "airport driver who has not cancelled once in 1,450 rides",
    scenario: "Large sample, perfect record — the strongest provider in the cast",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_imran:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_goride", type: "PROVIDER_RECORD", category: "rides", values: prov(1450, 1450, 0, 1442, 3), daysAgo: 520 }],
  },

  // ── Car rental ───────────────────────────────────────────────────────────
  {
    id: "usr_priya",
    name: "Priya",
    label: "car owner who handed over the keys in 58 of her 60 rentals",
    scenario: "Strong provider in a category where cancellation hurts the renter badly",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_priya:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_drivenow", type: "PROVIDER_RECORD", category: "car_rental", values: prov(58, 60, 1, 57, 0), daysAgo: 160 }],
  },
  {
    id: "usr_vikram",
    name: "Vikram",
    label: "car owner who cancels 3 in every 10 rentals after they are booked",
    scenario: "70% completion: the classic 'looks fine on the profile, fails the proof' case",
    tone: "amber",
    seed: "trustline-demo-holder:usr_vikram:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_drivenow", type: "PROVIDER_RECORD", category: "car_rental", values: prov(28, 40, 12, 30, 3), daysAgo: 90 }],
  },

  // ── Bikes and scooters ───────────────────────────────────────────────────
  {
    id: "usr_zoya",
    name: "Zoya",
    label: "scooter owner with 210 rentals and not one cancellation",
    scenario: "Another perfect provider, in a low-value category",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_zoya:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_pedalpoint", type: "PROVIDER_RECORD", category: "bikes", values: prov(210, 210, 0, 206, 1), daysAgo: 240 }],
  },
  {
    id: "usr_bhaskar",
    name: "Bhaskar",
    label: "bike owner who has completed only 1 of his last 10 rentals",
    scenario: "The 10% case: a provider whose profile looks active but who almost never delivers",
    tone: "rose",
    seed: "trustline-demo-holder:usr_bhaskar:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_pedalpoint", type: "PROVIDER_RECORD", category: "bikes", values: prov(1, 9, 8, 1, 4), daysAgo: 35 }],
  },

  // ── Dining ───────────────────────────────────────────────────────────────
  {
    id: "usr_courtyard",
    name: "The Courtyard Kitchen",
    label: "restaurant that held the table for 3,100 of 3,150 reservations",
    scenario: "A restaurant is a provider too, with a very large honoured-reservation count",
    tone: "rose",
    seed: "trustline-demo-holder:usr_courtyard:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_tablebook", type: "PROVIDER_RECORD", category: "dining", values: prov(3100, 3150, 12, 3050, 6), daysAgo: 800 }],
  },
  {
    id: "usr_spicebay",
    name: "Spice Bay",
    label: "restaurant that turned away 1 in 5 of the tables it had confirmed",
    scenario: "80% provider — passes a 75% check, fails a 90% one",
    tone: "amber",
    seed: "trustline-demo-holder:usr_spicebay:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_tablebook", type: "PROVIDER_RECORD", category: "dining", values: prov(400, 500, 96, 380, 24), daysAgo: 170 }],
  },

  // ── Groceries ────────────────────────────────────────────────────────────
  {
    id: "usr_farhan",
    name: "Farhan",
    label: "grocery store owner who delivered 1,340 of 1,382 orders",
    scenario: "High-volume reliable seller",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_farhan:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_freshcart", type: "PROVIDER_RECORD", category: "groceries", values: prov(1340, 1382, 22, 1310, 11), daysAgo: 600 }],
  },
  {
    id: "usr_rohan",
    name: "Rohan",
    label: "grocery seller with complaints on 27% of orders and wrong items half the time",
    scenario: "High dispute rate: completion looks acceptable, satisfaction does not",
    tone: "rose",
    seed: "trustline-demo-holder:usr_rohan:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_freshcart", type: "PROVIDER_RECORD", category: "groceries", values: prov(64, 80, 6, 40, 22), daysAgo: 150 }],
  },

  // ── Courier ──────────────────────────────────────────────────────────────
  {
    id: "usr_parcelrun",
    name: "ParcelRun Logistics",
    label: "courier company that delivered 9,800 of 10,000 parcels",
    scenario: "Business holder with a very large, very clean record",
    tone: "slate",
    seed: "trustline-demo-holder:usr_parcelrun:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_parcelpath", type: "PROVIDER_RECORD", category: "courier", values: prov(9800, 10000, 90, 9700, 110), daysAgo: 540 }],
  },
  {
    id: "usr_dashdrop",
    name: "DashDrop",
    label: "courier that delivered only 1 of its last 10 parcels",
    scenario: "A second 10% case, to show the pattern is not a one-off",
    tone: "rose",
    seed: "trustline-demo-holder:usr_dashdrop:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_parcelpath", type: "PROVIDER_RECORD", category: "courier", values: prov(1, 10, 6, 1, 5), daysAgo: 28 }],
  },

  // ── IT projects ──────────────────────────────────────────────────────────
  {
    id: "usr_sneha",
    name: "Sneha",
    label: "freelance developer who delivered all 23 projects she took on",
    scenario: "Perfect freelancer record over a believable sample",
    tone: "indigo",
    seed: "trustline-demo-holder:usr_sneha:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_devhire", type: "PROVIDER_RECORD", category: "it_projects", values: prov(23, 23, 0, 23, 0), daysAgo: 220 }],
  },
  {
    id: "usr_tarun",
    name: "Tarun",
    label: "freelancer who walked away from 7 of his last 20 projects",
    scenario: "65% completion with disputes — the case for checking before hiring",
    tone: "amber",
    seed: "trustline-demo-holder:usr_tarun:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_devhire", type: "PROVIDER_RECORD", category: "it_projects", values: prov(13, 20, 7, 11, 4), daysAgo: 110 }],
  },
  {
    id: "usr_omkar",
    name: "Omkar",
    label: "freelancer who has not finished a single one of the 14 projects he accepted",
    scenario: "The 0% case: every proof about completion fails, and honestly so",
    tone: "rose",
    seed: "trustline-demo-holder:usr_omkar:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_devhire", type: "PROVIDER_RECORD", category: "it_projects", values: prov(0, 14, 14, 0, 9), daysAgo: 70 }],
  },

  // ── Tutoring ─────────────────────────────────────────────────────────────
  {
    id: "usr_lata",
    name: "Lata",
    label: "maths tutor who taught 1,180 of the 1,200 sessions parents booked",
    scenario: "Long-running provider in a trust-sensitive category",
    tone: "indigo",
    seed: "trustline-demo-holder:usr_lata:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_learnloop", type: "PROVIDER_RECORD", category: "tutoring", values: prov(1180, 1200, 14, 1160, 8), daysAgo: 900 }],
  },
  {
    id: "usr_arnav",
    name: "Arnav",
    label: "coding tutor who started this term — 4 sessions booked, 4 taught",
    scenario: "Another limited-history holder, in a different category",
    tone: "sky",
    seed: "trustline-demo-holder:usr_arnav:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_learnloop", type: "PROVIDER_RECORD", category: "tutoring", values: prov(4, 4, 0, 4, 0), daysAgo: 16 }],
  },

  // ── Home services ────────────────────────────────────────────────────────
  {
    id: "usr_sunil",
    name: "Sunil",
    label: "electrician who finished 240 of the 250 jobs he was booked for",
    scenario: "Trades provider with a strong record",
    tone: "amber",
    seed: "trustline-demo-holder:usr_sunil:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_fixitnow", type: "PROVIDER_RECORD", category: "home_services", values: prov(240, 250, 8, 232, 6), daysAgo: 430 }],
  },
  {
    id: "usr_rakesh",
    name: "Rakesh",
    label: "plumber who accepts every job and turns up for about half of them",
    scenario: "A second 50% provider, in the category where a no-show costs the most",
    tone: "rose",
    seed: "trustline-demo-holder:usr_rakesh:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_fixitnow", type: "PROVIDER_RECORD", category: "home_services", values: prov(31, 62, 29, 28, 11), daysAgo: 95 }],
  },

  // ── Salon, clinic, pets, gear, desks, venues ─────────────────────────────
  {
    id: "usr_glowstudio",
    name: "Glow Studio",
    label: "salon that honoured 4,120 of 4,200 appointments",
    scenario: "Business provider with routine, high-frequency bookings",
    tone: "rose",
    seed: "trustline-demo-holder:usr_glowstudio:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_glowbar", type: "PROVIDER_RECORD", category: "beauty", values: prov(4120, 4200, 46, 4050, 34), daysAgo: 610 }],
  },
  {
    id: "usr_sunriseclinic",
    name: "Sunrise Clinic",
    label: "clinic that held the slot for 6,400 of 6,500 appointments — attendance only, no health data",
    scenario: "Shows a sensitive category where Trustline still records nothing but behaviour",
    tone: "sky",
    seed: "trustline-demo-holder:usr_sunriseclinic:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_medislot", type: "PROVIDER_RECORD", category: "healthcare", values: prov(6400, 6500, 60, 6320, 28), daysAgo: 680 }],
  },
  {
    id: "usr_anjali",
    name: "Anjali",
    label: "pet sitter who completed all 96 of her bookings",
    scenario: "Perfect provider in a category built almost entirely on trust",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_anjali:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_pawpals", type: "PROVIDER_RECORD", category: "pet_care", values: prov(96, 96, 0, 95, 0), daysAgo: 300 }],
  },
  {
    id: "usr_pawan",
    name: "Pawan",
    label: "pet sitter who cancelled or cut short 9 of his last 30 bookings",
    scenario: "70% provider with complaints attached",
    tone: "amber",
    seed: "trustline-demo-holder:usr_pawan:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_pawpals", type: "PROVIDER_RECORD", category: "pet_care", values: prov(21, 30, 9, 19, 5), daysAgo: 88 }],
  },
  {
    id: "usr_camerakart",
    name: "CameraKart",
    label: "camera rental shop with 780 of 800 rentals completed",
    scenario: "Business provider renting high-value goods",
    tone: "slate",
    seed: "trustline-demo-holder:usr_camerakart:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_gearvault", type: "PROVIDER_RECORD", category: "equipment", values: prov(780, 800, 14, 764, 12), daysAgo: 460 }],
  },
  {
    id: "usr_naveen",
    name: "Naveen",
    label: "gear owner who withdrew his own record, so nothing can be proven from it any more",
    scenario: "Revoked by the HOLDER, not the issuer — the other half of the revocation story",
    tone: "slate",
    seed: "trustline-demo-holder:usr_naveen:0",
    published: PUBLIC_PROVIDER,
    credentials: [
      {
        issuer: "org_gearvault",
        type: "PROVIDER_RECORD",
        category: "equipment",
        values: prov(44, 50, 5, 41, 3),
        daysAgo: 140,
        revokedDaysAgo: 4,
        revokedBy: "holder",
        revocationReason: "HOLDER_WITHDRAWN",
      },
    ],
  },
  {
    id: "usr_deskcompany",
    name: "The Desk Company",
    label: "coworking space that honoured 5,300 of 5,350 desk bookings",
    scenario: "Business provider with routine repeat customers",
    tone: "indigo",
    seed: "trustline-demo-holder:usr_deskcompany:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_deskhub", type: "PROVIDER_RECORD", category: "coworking", values: prov(5300, 5350, 30, 5240, 22), daysAgo: 520 }],
  },
  {
    id: "usr_grandhall",
    name: "Grand Hall Whitefield",
    label: "event venue that honoured 410 of 430 bookings",
    scenario: "High-value, low-frequency provider",
    tone: "amber",
    seed: "trustline-demo-holder:usr_grandhall:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_venuely", type: "PROVIDER_RECORD", category: "events", values: prov(410, 430, 14, 402, 9), daysAgo: 380 }],
  },
  {
    id: "usr_terracestudio",
    name: "Terrace Studio",
    label: "event space that double-books and then cancels 1 in 3 events",
    scenario: "A provider whose failure is expensive and last-minute",
    tone: "rose",
    seed: "trustline-demo-holder:usr_terracestudio:0",
    published: PUBLIC_PROVIDER,
    credentials: [{ issuer: "org_venuely", type: "PROVIDER_RECORD", category: "events", values: prov(40, 60, 20, 36, 12), daysAgo: 120 }],
  },

  // ── Customers ────────────────────────────────────────────────────────────
  {
    id: "usr_karan",
    name: "Karan",
    label: "guest who books and then does not turn up — he showed up for 3 of his 31 bookings",
    scenario: "The 10% customer: exactly the person a host wants to screen out",
    tone: "rose",
    seed: "trustline-demo-holder:usr_karan:0",
    published: ["verified_credentials"],
    credentials: [
      { issuer: "org_tripnest", type: "CUSTOMER_RECORD", category: "hotels", values: cust(2, 20, 2, 16, 2, 1), daysAgo: 80 },
      { issuer: "org_tablebook", type: "CUSTOMER_RECORD", category: "dining", values: cust(1, 11, 0, 10, 1, 0), daysAgo: 40 },
    ],
  },
  {
    id: "usr_ananya",
    name: "Ananya",
    label: "guest who nearly always turns up, but cancels 37% of what she books",
    scenario: "Good on one metric, poor on another — why there is no single trust score",
    tone: "sky",
    seed: "trustline-demo-holder:usr_ananya:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_citystay", type: "CUSTOMER_RECORD", category: "stays", values: cust(18, 30, 11, 1, 18, 0), daysAgo: 70 }],
  },
  {
    id: "usr_aisha",
    name: "Aisha",
    label: "renter who failed to collect the car 9 times out of 40 bookings",
    scenario: "75% booking reliability — passes a lenient check, fails a strict one",
    tone: "amber",
    seed: "trustline-demo-holder:usr_aisha:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_drivenow", type: "CUSTOMER_RECORD", category: "car_rental", values: cust(27, 40, 4, 9, 27, 1), daysAgo: 100 }],
  },
  {
    id: "usr_nikhil",
    name: "Nikhil",
    label: "IT client who finishes projects but paid only 5 of 10 invoices as agreed",
    scenario: "Payment reliability is its own metric, and his is the one that fails",
    tone: "slate",
    seed: "trustline-demo-holder:usr_nikhil:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_devhire", type: "CUSTOMER_RECORD", category: "it_projects", values: cust(10, 12, 2, 0, 5, 4), daysAgo: 60 }],
  },
  {
    id: "usr_rahul",
    name: "Rahul",
    label: "passenger with 310 completed rides and a single no-show",
    scenario: "Excellent customer with a large sample",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_rahul:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_goride", type: "CUSTOMER_RECORD", category: "rides", values: cust(310, 312, 1, 1, 310, 0), daysAgo: 300 }],
  },
  {
    id: "usr_divya",
    name: "Divya",
    label: "shopper with exactly one completed order — 100%, but from a single data point",
    scenario: "Limited history on the customer side",
    tone: "sky",
    seed: "trustline-demo-holder:usr_divya:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_freshcart", type: "CUSTOMER_RECORD", category: "groceries", values: cust(1, 1, 0, 0, 1, 0), daysAgo: 3 }],
  },
  {
    id: "usr_zaid",
    name: "Zaid",
    label: "traveller who booked 8 flights and boarded none of them",
    scenario: "The 0% customer: every reliability proof fails",
    tone: "rose",
    seed: "trustline-demo-holder:usr_zaid:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_skyfare", type: "CUSTOMER_RECORD", category: "flights", values: cust(0, 8, 0, 8, 0, 2), daysAgo: 50 }],
  },
  {
    id: "usr_neha",
    name: "Neha",
    label: "shopper with 520 orders — every one received and paid for",
    scenario: "A flawless customer at scale, the mirror image of Zaid",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_neha:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_freshcart", type: "CUSTOMER_RECORD", category: "groceries", values: cust(520, 520, 0, 0, 520, 0), daysAgo: 420 }],
  },
  {
    id: "usr_gaurav",
    name: "Gaurav",
    label: "customer who always shows up but has settled only 12 of his 24 bills as agreed",
    scenario: "50% payment reliability with 100% attendance — two metrics pulling apart",
    tone: "amber",
    seed: "trustline-demo-holder:usr_gaurav:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_fixitnow", type: "CUSTOMER_RECORD", category: "home_services", values: cust(24, 24, 0, 0, 12, 6), daysAgo: 115 }],
  },
  {
    id: "usr_maya",
    name: "Maya",
    label: "sells handmade goods and buys groceries — one Trustline covering both sides of her life",
    scenario: "Dual role: buyer metrics and seller metrics on the same holder",
    tone: "indigo",
    seed: "trustline-demo-holder:usr_maya:0",
    published: PUBLIC_BOTH,
    credentials: [
      {
        issuer: "org_marketplace_a",
        type: "MARKETPLACE_REPUTATION",
        values: {
          successful_transactions: 64,
          bookings_total: 70,
          cancellations: 4,
          no_shows: 2,
          payments_completed: 64,
          disputes: 1,
          seller_orders_accepted: 120,
          seller_orders_completed: 114,
          seller_cancellations: 6,
          seller_positive_outcomes: 110,
          seller_disputes: 4,
        },
        daysAgo: 190,
      },
      { issuer: "org_freshcart", type: "CUSTOMER_RECORD", category: "groceries", values: cust(88, 92, 3, 1, 88, 0), daysAgo: 55 },
    ],
  },
  {
    id: "usr_tanvi",
    name: "Tanvi",
    label: "guest with exactly 20 completed bookings — proves “20 or more”, fails “21 or more”",
    scenario: "The boundary case, for showing that the proof is exact and not fuzzy",
    tone: "indigo",
    seed: "trustline-demo-holder:usr_tanvi:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_tripnest", type: "CUSTOMER_RECORD", category: "hotels", values: cust(20, 20, 0, 0, 20, 0), daysAgo: 135 }],
  },
  {
    id: "usr_harsh",
    name: "Harsh",
    label: "student whose tutoring record was revoked, but whose salon record is still valid",
    scenario: "Holds a dead credential and a live one: the wallet must pick the live one",
    tone: "sky",
    seed: "trustline-demo-holder:usr_harsh:0",
    published: PUBLIC_CUSTOMER,
    credentials: [
      {
        issuer: "org_learnloop",
        type: "CUSTOMER_RECORD",
        category: "tutoring",
        values: cust(30, 34, 3, 1, 30, 0),
        daysAgo: 210,
        revokedDaysAgo: 7,
        revokedBy: "issuer",
        revocationReason: "ISSUER_CORRECTION",
      },
      { issuer: "org_glowbar", type: "CUSTOMER_RECORD", category: "beauty", values: cust(26, 28, 2, 0, 26, 0), daysAgo: 64 },
    ],
  },
  {
    id: "usr_pooja",
    name: "Pooja",
    label: "diner whose only record is nearly three years old, so nothing recent is verifiable",
    scenario: "Stale history: the numbers are good but they are old, and the UI says so",
    tone: "slate",
    seed: "trustline-demo-holder:usr_pooja:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_tablebook", type: "CUSTOMER_RECORD", category: "dining", values: cust(46, 48, 2, 0, 46, 0), daysAgo: 1020 }],
  },
  {
    id: "usr_faiz",
    name: "Faiz",
    label: "member who books desks constantly — 640 bookings, 9 of them unused",
    scenario: "High-frequency, low-value customer with a very good record",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_faiz:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_deskhub", type: "CUSTOMER_RECORD", category: "coworking", values: cust(631, 640, 4, 5, 631, 0), daysAgo: 350 }],
  },
  {
    id: "usr_shreya",
    name: "Shreya",
    label: "pet owner with a clean record on one platform and no record anywhere else",
    scenario: "Single-platform holder: shows what cross-platform portability adds",
    tone: "emerald",
    seed: "trustline-demo-holder:usr_shreya:0",
    published: PUBLIC_CUSTOMER,
    credentials: [{ issuer: "org_pawpals", type: "CUSTOMER_RECORD", category: "pet_care", values: cust(17, 18, 1, 0, 17, 0), daysAgo: 92 }],
  },
  {
    id: "usr_dev",
    name: "Dev",
    label: "traveller who has never held a Trustline credential — a completely blank customer",
    scenario: "Zero history on the customer side, mirroring NewHost23 on the provider side",
    tone: "slate",
    seed: "trustline-demo-holder:usr_dev:0",
    published: PUBLIC_CUSTOMER,
    credentials: [],
  },
];

export const personLabel = (id: string) => PEOPLE.find((p) => p.id === id)?.label;
export const personName = (id: string) => PEOPLE.find((p) => p.id === id)?.name ?? "Someone";

/** "Karan (guest who books and then does not turn up…)" */
export function withLabel(name: string, id: string) {
  const label = personLabel(id);
  return label ? `${name} (${label})` : name;
}

// ── Listings ────────────────────────────────────────────────────────────────

type ListingSeed = Omit<Listing, "providerName" | "providerLabel"> & { providerName?: string };

/** Keeps every listing's bracketed provider description identical to the cast. */
function listing(seed: ListingSeed): Listing {
  const person = PEOPLE.find((p) => p.id === seed.providerUserId);
  if (!person) throw new Error(`Listing ${seed.id} has no cast member ${seed.providerUserId}`);
  return { ...seed, providerName: seed.providerName ?? person.name, providerLabel: person.label };
}

const SAND: [string, string, string] = ["#E9E4DA", "#CBBFA8", "#8E7F66"];
const LEAF: [string, string, string] = ["#E2E8DF", "#B7C6AE", "#6F8565"];
const CLAY: [string, string, string] = ["#EDE3DE", "#D0B5A8", "#946F5E"];
const SLATE: [string, string, string] = ["#E3E6EA", "#B9C0CA", "#6D7785"];
const OCEAN: [string, string, string] = ["#E1E7EE", "#AFC0D3", "#5E7894"];
const PLUM: [string, string, string] = ["#EDE5EE", "#CDB5D0", "#7B5282"];
const WHEAT: [string, string, string] = ["#EFE9DF", "#D6C4A2", "#8F7446"];
const MINT: [string, string, string] = ["#E5EDE0", "#B4CBA6", "#5E8250"];
const IRIS: [string, string, string] = ["#E6E6F2", "#BDBDE0", "#4F4F9A"];
const EMBER: [string, string, string] = ["#EEE6E4", "#D3B9B3", "#9A5B4E"];

export const LISTINGS: Listing[] = [
  // Stays
  listing({
    id: "lst_modern_apartment",
    category: "stays",
    title: "Modern Apartment",
    city: "Bangalore",
    neighbourhood: "Indiranagar",
    price: 2400,
    providerUserId: "usr_arjun",
    providerSince: "2019",
    rating: 4.9,
    reviewCount: 118,
    highlights: ["3 guests", "1 bedroom", "Fast Wi-Fi", "Workspace", "Self check-in"],
    description: "A bright one-bedroom on a quiet lane off 100 Feet Road, walking distance from the metro.",
    palette: SAND,
    tag: "Guest favourite",
  }),
  listing({
    id: "lst_garden_flat",
    category: "stays",
    title: "Garden Flat with Balcony",
    city: "Bangalore",
    neighbourhood: "Koramangala",
    price: 3100,
    providerUserId: "usr_meera",
    providerSince: "2021",
    rating: 4.8,
    reviewCount: 57,
    highlights: ["4 guests", "2 bedrooms", "Balcony", "Parking"],
    description: "Two bedrooms facing a leafy courtyard in 5th Block. Good for small families.",
    palette: LEAF,
  }),
  listing({
    id: "lst_heritage_loft",
    category: "stays",
    title: "Heritage Loft, Basavanagudi",
    city: "Bangalore",
    neighbourhood: "Basavanagudi",
    price: 2750,
    providerUserId: "usr_kabir",
    providerSince: "2017",
    rating: 4.3,
    reviewCount: 203,
    highlights: ["2 guests", "Terrace", "Breakfast"],
    description: "A restored 1950s loft above a quiet bylane, minutes from Gandhi Bazaar.",
    palette: CLAY,
  }),
  listing({
    id: "lst_cozy_studio",
    category: "stays",
    title: "Cozy Studio near MG Road",
    city: "Bangalore",
    neighbourhood: "Richmond Town",
    price: 1650,
    providerUserId: "usr_newhost23",
    providerSince: "2026",
    highlights: ["2 guests", "Kitchenette"],
    description: "Compact studio close to MG Road. Newly listed, with no reviews yet.",
    palette: SLATE,
    tag: "New listing",
  }),
  listing({
    id: "lst_budget_room",
    category: "stays",
    title: "Budget Room near Majestic",
    city: "Bangalore",
    neighbourhood: "Gandhinagar",
    price: 899,
    providerUserId: "usr_quickstays",
    providerSince: "2024",
    rating: 3.9,
    reviewCount: 41,
    highlights: ["1 guest", "Near bus stand"],
    description: "A basic room close to the city bus stand and railway station.",
    palette: SAND,
  }),
  listing({
    id: "lst_hilltop_cottage",
    category: "stays",
    title: "Hilltop Cottage",
    city: "Coorg",
    neighbourhood: "Madikeri",
    price: 4200,
    providerUserId: "usr_ishita",
    providerSince: "2026",
    rating: 5,
    reviewCount: 2,
    highlights: ["4 guests", "Coffee estate", "Bonfire"],
    description: "A two-bedroom cottage on the edge of a working coffee estate.",
    palette: LEAF,
    tag: "New host",
  }),
  listing({
    id: "lst_lake_house",
    category: "stays",
    title: "Lake House, Hebbal",
    city: "Bangalore",
    neighbourhood: "Hebbal",
    price: 3600,
    providerUserId: "usr_devansh",
    providerSince: "2022",
    rating: 4,
    reviewCount: 35,
    highlights: ["6 guests", "Lake view", "Parking"],
    description: "Large family house overlooking Hebbal Lake.",
    palette: OCEAN,
  }),

  // Hotels
  listing({
    id: "lst_lakeview_room",
    category: "hotels",
    title: "Deluxe Room, Lakeview Residency",
    city: "Bangalore",
    neighbourhood: "Ulsoor Lake",
    price: 5200,
    providerUserId: "usr_lakeview",
    providerSince: "2011",
    rating: 4.6,
    reviewCount: 1840,
    highlights: ["Lake view", "Breakfast included", "Pool", "24h desk"],
    description: "A calm business hotel on the edge of Ulsoor Lake.",
    palette: OCEAN,
  }),
  listing({
    id: "lst_bluepalm_room",
    category: "hotels",
    title: "Standard Room, Blue Palm Inn",
    city: "Mysuru",
    neighbourhood: "Near Palace Road",
    price: 1899,
    providerUserId: "usr_bluepalm",
    providerSince: "2015",
    rating: 3.8,
    reviewCount: 460,
    highlights: ["AC", "Breakfast", "Walk to palace"],
    description: "Budget rooms a short walk from the Mysore Palace gates.",
    palette: SLATE,
  }),

  // Flights
  listing({
    id: "lst_skybird_blr_del",
    category: "flights",
    title: "Bangalore → Delhi, morning direct",
    city: "Bangalore",
    neighbourhood: "BLR → DEL",
    price: 4890,
    providerUserId: "usr_skybird",
    providerSince: "2009",
    rating: 4.4,
    reviewCount: 9800,
    highlights: ["Direct", "2h 45m", "Cabin bag included"],
    description: "Early-morning direct service with checked baggage available at booking.",
    palette: OCEAN,
  }),
  listing({
    id: "lst_fareloop_goa",
    category: "flights",
    title: "Bangalore → Goa, discounted fare",
    city: "Bangalore",
    neighbourhood: "BLR → GOI",
    price: 2450,
    providerUserId: "usr_fareloop",
    providerSince: "2020",
    rating: 3.2,
    reviewCount: 310,
    highlights: ["Agent fare", "Non-refundable"],
    description: "A cheap agent-issued fare on a popular weekend route.",
    palette: EMBER,
  }),

  // Tours and experiences
  listing({
    id: "lst_kudremukh_trek",
    category: "experiences",
    title: "Kudremukh sunrise trek",
    city: "Chikkamagaluru",
    neighbourhood: "Kudremukh",
    price: 2300,
    providerUserId: "usr_tenzin",
    providerSince: "2018",
    rating: 4.9,
    reviewCount: 86,
    highlights: ["Guide", "Permits", "Breakfast"],
    description: "A guided pre-dawn climb with permits and breakfast included.",
    palette: MINT,
    tag: "Top rated",
  }),
  listing({
    id: "lst_heritage_walk",
    category: "experiences",
    title: "Old Bangalore heritage walk",
    city: "Bangalore",
    neighbourhood: "Chickpet",
    price: 750,
    providerUserId: "usr_ritika",
    providerSince: "2021",
    rating: 4.2,
    reviewCount: 48,
    highlights: ["3 hours", "Small group", "Chai stop"],
    description: "A morning walk through the markets and temples of the old town.",
    palette: WHEAT,
  }),

  // Rides
  listing({
    id: "lst_airport",
    category: "rides",
    title: "Airport transfer · sedan",
    city: "Bangalore",
    neighbourhood: "City → KIA Airport",
    price: 1150,
    providerUserId: "usr_suresh",
    providerSince: "2018",
    rating: 4.4,
    reviewCount: 790,
    highlights: ["Sedan", "4 seats", "Luggage space"],
    description: "Fixed-price transfer to Kempegowda International Airport.",
    palette: LEAF,
  }),
  listing({
    id: "lst_mysuru",
    category: "rides",
    title: "Outstation cab to Mysuru",
    city: "Bangalore",
    neighbourhood: "Bangalore → Mysuru",
    price: 3400,
    providerUserId: "usr_manoj",
    providerSince: "2026",
    highlights: ["SUV", "6 seats", "One way"],
    description: "Comfortable SUV for the Mysuru highway run.",
    palette: MINT,
    tag: "New driver",
  }),
  listing({
    id: "lst_night_airport",
    category: "rides",
    title: "Night airport pickup · premium",
    city: "Bangalore",
    neighbourhood: "KIA Airport → City",
    price: 1450,
    providerUserId: "usr_imran",
    providerSince: "2016",
    rating: 5,
    reviewCount: 1450,
    highlights: ["Meet and greet", "Flight tracking", "24h"],
    description: "Late-night pickups with flight tracking and a 60-minute free wait.",
    palette: SLATE,
    tag: "Never cancelled",
  }),

  // Car rental
  listing({
    id: "lst_creta",
    category: "car_rental",
    title: "Hyundai Creta · self-drive",
    city: "Bangalore",
    neighbourhood: "HSR Layout",
    price: 2900,
    providerUserId: "usr_priya",
    providerSince: "2022",
    rating: 4.9,
    reviewCount: 52,
    highlights: ["Automatic", "5 seats", "Petrol", "Unlimited km"],
    description: "Well-kept 2023 Creta. Pickup from HSR Layout, fuel-to-fuel.",
    palette: SLATE,
  }),
  listing({
    id: "lst_swift",
    category: "car_rental",
    title: "Maruti Swift · self-drive",
    city: "Bangalore",
    neighbourhood: "Marathahalli",
    price: 1500,
    providerUserId: "usr_vikram",
    providerSince: "2023",
    rating: 4.1,
    reviewCount: 26,
    highlights: ["Manual", "5 seats", "Petrol"],
    description: "Compact hatchback for city runs.",
    palette: EMBER,
  }),

  // Bikes
  listing({
    id: "lst_activa",
    category: "bikes",
    title: "Honda Activa · daily rental",
    city: "Bangalore",
    neighbourhood: "Jayanagar",
    price: 399,
    providerUserId: "usr_zoya",
    providerSince: "2021",
    rating: 4.8,
    reviewCount: 210,
    highlights: ["Helmet included", "Fuel extra"],
    description: "A serviced Activa with a helmet, handed over at the metro station.",
    palette: MINT,
  }),
  listing({
    id: "lst_royal_enfield",
    category: "bikes",
    title: "Royal Enfield Classic 350",
    city: "Bangalore",
    neighbourhood: "Whitefield",
    price: 1200,
    providerUserId: "usr_bhaskar",
    providerSince: "2024",
    rating: 3.1,
    reviewCount: 9,
    highlights: ["500 km limit", "Saddle bags"],
    description: "Weekend touring bike with luggage mounts.",
    palette: EMBER,
  }),

  // Dining
  listing({
    id: "lst_courtyard",
    category: "dining",
    title: "Dinner for two",
    city: "Bangalore",
    neighbourhood: "Lavelle Road",
    price: 2600,
    providerUserId: "usr_courtyard",
    providerSince: "2014",
    rating: 4.7,
    reviewCount: 2900,
    highlights: ["Garden seating", "Veg & non-veg"],
    description: "A courtyard restaurant with a seasonal South Indian menu.",
    palette: WHEAT,
  }),
  listing({
    id: "lst_spicebay",
    category: "dining",
    title: "Weekend table for four",
    city: "Bangalore",
    neighbourhood: "Church Street",
    price: 3200,
    providerUserId: "usr_spicebay",
    providerSince: "2019",
    rating: 4,
    reviewCount: 540,
    highlights: ["Coastal menu", "Bar"],
    description: "Coastal plates and a small bar on a busy street.",
    palette: CLAY,
  }),

  // Groceries
  listing({
    id: "lst_freshmart",
    category: "groceries",
    title: "Weekly vegetable & fruit basket",
    city: "Bangalore",
    neighbourhood: "Jayanagar",
    price: 849,
    providerUserId: "usr_farhan",
    providerName: "Farhan's FreshMart",
    providerSince: "2016",
    rating: 4.7,
    reviewCount: 1210,
    highlights: ["Same-day delivery", "8 kg", "Seasonal"],
    description: "Seasonal vegetables and fruit, packed fresh each morning.",
    palette: MINT,
  }),
  listing({
    id: "lst_dailyneeds",
    category: "groceries",
    title: "Monthly staples pack",
    city: "Bangalore",
    neighbourhood: "BTM Layout",
    price: 2199,
    providerUserId: "usr_rohan",
    providerName: "Rohan's Daily Needs",
    providerSince: "2024",
    rating: 3.4,
    reviewCount: 74,
    highlights: ["Rice, dal, oil", "Next-day delivery"],
    description: "Rice, dals, atta, oil and spices for a family of four.",
    palette: WHEAT,
  }),

  // Courier
  listing({
    id: "lst_parcelrun_citywide",
    category: "courier",
    title: "Same-day city parcel",
    city: "Bangalore",
    neighbourhood: "Citywide",
    price: 180,
    providerUserId: "usr_parcelrun",
    providerSince: "2013",
    rating: 4.6,
    reviewCount: 9800,
    highlights: ["Up to 5 kg", "Tracked", "Insured"],
    description: "Point-to-point delivery anywhere inside the city, same day.",
    palette: SLATE,
  }),
  listing({
    id: "lst_dashdrop_express",
    category: "courier",
    title: "Express two-hour drop",
    city: "Bangalore",
    neighbourhood: "Central zone",
    price: 320,
    providerUserId: "usr_dashdrop",
    providerSince: "2025",
    rating: 2.4,
    reviewCount: 11,
    highlights: ["2 hours", "Up to 2 kg"],
    description: "A fast two-hour promise inside the central zone.",
    palette: EMBER,
  }),

  // IT projects
  listing({
    id: "lst_nextjs_site",
    category: "it_projects",
    title: "Business website in Next.js",
    city: "Remote",
    neighbourhood: "Bangalore · remote",
    price: 45000,
    providerUserId: "usr_sneha",
    providerSince: "2020",
    rating: 5,
    reviewCount: 23,
    highlights: ["5 pages", "CMS", "2-week delivery"],
    description: "A fast, accessible marketing site with a headless CMS.",
    palette: IRIS,
  }),
  listing({
    id: "lst_app_mvp",
    category: "it_projects",
    title: "Mobile app MVP (Flutter)",
    city: "Remote",
    neighbourhood: "Pune · remote",
    price: 120000,
    providerUserId: "usr_tarun",
    providerSince: "2022",
    rating: 3.8,
    reviewCount: 16,
    highlights: ["iOS + Android", "6-week estimate"],
    description: "Cross-platform MVP with login, payments and push notifications.",
    palette: PLUM,
  }),
  listing({
    id: "lst_data_pipeline",
    category: "it_projects",
    title: "Data pipeline setup",
    city: "Remote",
    neighbourhood: "Hyderabad · remote",
    price: 90000,
    providerUserId: "usr_omkar",
    providerSince: "2023",
    rating: 2.1,
    reviewCount: 14,
    highlights: ["ETL", "Dashboards"],
    description: "Ingestion, transformation and a reporting dashboard.",
    palette: EMBER,
  }),

  // Tutoring
  listing({
    id: "lst_maths_tuition",
    category: "tutoring",
    title: "Class 10 maths, one-to-one",
    city: "Bangalore",
    neighbourhood: "Malleshwaram",
    price: 900,
    providerUserId: "usr_lata",
    providerName: "Lata",
    providerSince: "2009",
    rating: 4.9,
    reviewCount: 1180,
    highlights: ["60 minutes", "Home or online"],
    description: "Board-exam maths coaching, one student at a time.",
    palette: IRIS,
  }),
  listing({
    id: "lst_python_classes",
    category: "tutoring",
    title: "Python for beginners, small batch",
    city: "Bangalore",
    neighbourhood: "Online",
    price: 650,
    providerUserId: "usr_arnav",
    providerSince: "2026",
    rating: 5,
    reviewCount: 4,
    highlights: ["90 minutes", "Max 6 students"],
    description: "A weekend batch that starts from nothing and ends with a small project.",
    palette: SLATE,
    tag: "New tutor",
  }),

  // Home services
  listing({
    id: "lst_electrical_visit",
    category: "home_services",
    title: "Electrical fault visit",
    city: "Bangalore",
    neighbourhood: "Citywide",
    price: 550,
    providerUserId: "usr_sunil",
    providerSince: "2014",
    rating: 4.7,
    reviewCount: 240,
    highlights: ["Same-day", "Parts extra"],
    description: "Diagnosis and repair for wiring, switches and fixtures.",
    palette: WHEAT,
  }),
  listing({
    id: "lst_plumbing_visit",
    category: "home_services",
    title: "Plumbing repair visit",
    city: "Bangalore",
    neighbourhood: "South Bangalore",
    price: 480,
    providerUserId: "usr_rakesh",
    providerSince: "2020",
    rating: 3,
    reviewCount: 62,
    highlights: ["Leaks", "Fittings"],
    description: "Leak repairs, tap and fitting replacement.",
    palette: EMBER,
  }),

  // Beauty
  listing({
    id: "lst_glow_haircut",
    category: "beauty",
    title: "Haircut and styling",
    city: "Bangalore",
    neighbourhood: "Indiranagar",
    price: 900,
    providerUserId: "usr_glowstudio",
    providerSince: "2015",
    rating: 4.6,
    reviewCount: 4120,
    highlights: ["45 minutes", "Wash included"],
    description: "Cut, wash and blow-dry with a senior stylist.",
    palette: CLAY,
  }),

  // Healthcare
  listing({
    id: "lst_clinic_slot",
    category: "healthcare",
    title: "General physician consultation",
    city: "Bangalore",
    neighbourhood: "Jayanagar",
    price: 600,
    providerUserId: "usr_sunriseclinic",
    providerSince: "2008",
    rating: 4.5,
    reviewCount: 6400,
    highlights: ["15-minute slot", "Walk-in desk"],
    description: "A booked slot with a general physician. Trustline records attendance only.",
    palette: OCEAN,
  }),

  // Pet care
  listing({
    id: "lst_pet_boarding",
    category: "pet_care",
    title: "Dog boarding at a home",
    city: "Bangalore",
    neighbourhood: "Sarjapur Road",
    price: 800,
    providerUserId: "usr_anjali",
    providerSince: "2019",
    rating: 4.9,
    reviewCount: 96,
    highlights: ["Home stay", "Two walks daily", "Photo updates"],
    description: "Your dog stays in a home, not a kennel, with two walks a day.",
    palette: MINT,
  }),
  listing({
    id: "lst_pet_daycare",
    category: "pet_care",
    title: "Daytime pet sitting",
    city: "Bangalore",
    neighbourhood: "Banashankari",
    price: 450,
    providerUserId: "usr_pawan",
    providerSince: "2022",
    rating: 3.6,
    reviewCount: 30,
    highlights: ["9am–6pm", "Feeding included"],
    description: "Daytime care while you are at work.",
    palette: WHEAT,
  }),

  // Equipment
  listing({
    id: "lst_camera_kit",
    category: "equipment",
    title: "Sony A7 IV camera kit",
    city: "Bangalore",
    neighbourhood: "Koramangala",
    price: 2200,
    providerUserId: "usr_camerakart",
    providerSince: "2017",
    rating: 4.8,
    reviewCount: 780,
    highlights: ["Body + 24-70mm", "2 batteries", "Insured"],
    description: "Full-frame body with a fast zoom, batteries and a card.",
    palette: SLATE,
  }),
  listing({
    id: "lst_drone_kit",
    category: "equipment",
    title: "Drone with ND filters",
    city: "Bangalore",
    neighbourhood: "Yelahanka",
    price: 1800,
    providerUserId: "usr_naveen",
    providerSince: "2021",
    rating: 4.2,
    reviewCount: 44,
    highlights: ["4K", "3 batteries"],
    description: "Compact drone kit for outdoor shoots.",
    palette: OCEAN,
  }),

  // Coworking
  listing({
    id: "lst_hot_desk",
    category: "coworking",
    title: "Hot desk, day pass",
    city: "Bangalore",
    neighbourhood: "Domlur",
    price: 550,
    providerUserId: "usr_deskcompany",
    providerSince: "2016",
    rating: 4.7,
    reviewCount: 5300,
    highlights: ["Wi-Fi", "Coffee", "Phone booths"],
    description: "A desk for the day with meeting-room credits included.",
    palette: IRIS,
  }),

  // Events
  listing({
    id: "lst_grand_hall",
    category: "events",
    title: "Banquet hall, 200 guests",
    city: "Bangalore",
    neighbourhood: "Whitefield",
    price: 65000,
    providerUserId: "usr_grandhall",
    providerSince: "2012",
    rating: 4.5,
    reviewCount: 410,
    highlights: ["200 guests", "Parking", "Catering allowed"],
    description: "A full-day hall booking with parking and in-house sound.",
    palette: WHEAT,
  }),
  listing({
    id: "lst_terrace_studio",
    category: "events",
    title: "Rooftop studio for shoots",
    city: "Bangalore",
    neighbourhood: "Frazer Town",
    price: 12000,
    providerUserId: "usr_terracestudio",
    providerSince: "2023",
    rating: 3.3,
    reviewCount: 60,
    highlights: ["Open air", "Power backup"],
    description: "An open rooftop with power and a small green room.",
    palette: EMBER,
  }),
];

// ── Completed OneCity transactions with two-sided feedback ──────────────────

export interface SeededTransaction {
  customer: string;
  listing: string;
  quantity: number;
  daysAgo: number;
  customerSays: { serviceCompleted: boolean; listingAccurate: boolean; hostCancelled: boolean };
  providerSays: { guestShowedUp: boolean; paidAsAgreed: boolean; guestCancelled: boolean };
  /**
   * The provider turned the request down, for this reason. Nothing is
   * completed, no feedback is given and no credential is issued — a request
   * that never became a transaction leaves no mark on anyone.
   */
  declinedBecause?: string;
  /** Left outstanding, so the provider still has a decision to make. */
  awaitingDecision?: boolean;
}

const good = {
  customerSays: { serviceCompleted: true, listingAccurate: true, hostCancelled: false },
  providerSays: { guestShowedUp: true, paidAsAgreed: true, guestCancelled: false },
};
/** The provider delivered; the customer never turned up. */
const noShow = {
  customerSays: { serviceCompleted: false, listingAccurate: true, hostCancelled: false },
  providerSays: { guestShowedUp: false, paidAsAgreed: false, guestCancelled: false },
};
/** The provider cancelled after confirming. */
const providerCancelled = {
  customerSays: { serviceCompleted: false, listingAccurate: true, hostCancelled: true },
  providerSays: { guestShowedUp: true, paidAsAgreed: true, guestCancelled: false },
};
/** The customer cancelled in advance — bad for them, not for the provider. */
const customerCancelled = {
  customerSays: { serviceCompleted: false, listingAccurate: true, hostCancelled: false },
  providerSays: { guestShowedUp: false, paidAsAgreed: false, guestCancelled: true },
};
/** Delivered, but not what the listing described. */
const inaccurate = {
  customerSays: { serviceCompleted: true, listingAccurate: false, hostCancelled: false },
  providerSays: { guestShowedUp: true, paidAsAgreed: true, guestCancelled: false },
};
/** The provider walked off the job and the customer never paid for it. */
const abandonedAndUnpaid = {
  customerSays: { serviceCompleted: false, listingAccurate: false, hostCancelled: true },
  providerSays: { guestShowedUp: true, paidAsAgreed: false, guestCancelled: false },
};
/** Delivered, and the customer did not pay as agreed. */
const unpaid = {
  customerSays: { serviceCompleted: true, listingAccurate: true, hostCancelled: false },
  providerSays: { guestShowedUp: true, paidAsAgreed: false, guestCancelled: false },
};

/**
 * Vineet is deliberately absent: his OneCity trips are booked live during the
 * demo, so his four platform credentials are the only thing behind his numbers.
 */
export const SEEDED_TRANSACTIONS: SeededTransaction[] = [
  { customer: "usr_ananya", listing: "lst_garden_flat", quantity: 2, daysAgo: 46, ...good },
  { customer: "usr_neha", listing: "lst_freshmart", quantity: 1, daysAgo: 44, ...good },
  { customer: "usr_karan", listing: "lst_heritage_loft", quantity: 1, daysAgo: 42, ...noShow },
  { customer: "usr_faiz", listing: "lst_hot_desk", quantity: 3, daysAgo: 40, ...good },
  { customer: "usr_rahul", listing: "lst_airport", quantity: 1, daysAgo: 38, ...good },
  { customer: "usr_zaid", listing: "lst_skybird_blr_del", quantity: 1, daysAgo: 36, ...noShow },
  { customer: "usr_aisha", listing: "lst_swift", quantity: 2, daysAgo: 34, ...providerCancelled },
  { customer: "usr_maya", listing: "lst_dailyneeds", quantity: 1, daysAgo: 32, ...inaccurate },
  { customer: "usr_gaurav", listing: "lst_electrical_visit", quantity: 1, daysAgo: 30, ...unpaid },
  { customer: "usr_shreya", listing: "lst_pet_boarding", quantity: 4, daysAgo: 29, ...good },
  { customer: "usr_tanvi", listing: "lst_lakeview_room", quantity: 2, daysAgo: 28, ...good },
  { customer: "usr_aisha", listing: "lst_creta", quantity: 3, daysAgo: 26, ...good },
  { customer: "usr_harsh", listing: "lst_python_classes", quantity: 2, daysAgo: 25, ...good },
  { customer: "usr_pooja", listing: "lst_courtyard", quantity: 1, daysAgo: 24, ...good },
  { customer: "usr_divya", listing: "lst_dailyneeds", quantity: 1, daysAgo: 22, ...inaccurate },
  { customer: "usr_nikhil", listing: "lst_app_mvp", quantity: 1, daysAgo: 20, ...abandonedAndUnpaid },
  { customer: "usr_neha", listing: "lst_parcelrun_citywide", quantity: 1, daysAgo: 19, ...good },
  { customer: "usr_gaurav", listing: "lst_plumbing_visit", quantity: 1, daysAgo: 18, ...providerCancelled },
  { customer: "usr_rahul", listing: "lst_mysuru", quantity: 1, daysAgo: 17, ...good },
  { customer: "usr_maya", listing: "lst_activa", quantity: 2, daysAgo: 16, ...good },
  { customer: "usr_zaid", listing: "lst_fareloop_goa", quantity: 1, daysAgo: 15, ...noShow },
  { customer: "usr_ananya", listing: "lst_lake_house", quantity: 2, daysAgo: 13, ...customerCancelled },
  { customer: "usr_faiz", listing: "lst_clinic_slot", quantity: 1, daysAgo: 12, ...good },
  { customer: "usr_tanvi", listing: "lst_heritage_walk", quantity: 2, daysAgo: 11, ...providerCancelled },
  { customer: "usr_harsh", listing: "lst_royal_enfield", quantity: 1, daysAgo: 10, ...providerCancelled },
  { customer: "usr_karan", listing: "lst_courtyard", quantity: 1, daysAgo: 9, ...noShow },
  { customer: "usr_shreya", listing: "lst_pet_daycare", quantity: 1, daysAgo: 8, ...providerCancelled },
  { customer: "usr_pooja", listing: "lst_maths_tuition", quantity: 4, daysAgo: 7, ...good },
  { customer: "usr_divya", listing: "lst_freshmart", quantity: 1, daysAgo: 6, ...good },
  { customer: "usr_ananya", listing: "lst_lakeview_room", quantity: 1, daysAgo: 5, ...customerCancelled },
  { customer: "usr_nikhil", listing: "lst_nextjs_site", quantity: 1, daysAgo: 4, ...good },
  { customer: "usr_neha", listing: "lst_camera_kit", quantity: 2, daysAgo: 3, ...good },
  { customer: "usr_gaurav", listing: "lst_dashdrop_express", quantity: 1, daysAgo: 2, ...providerCancelled },

  // ── Requests the provider turned down after reading the Trustline ───────
  // The feedback below never happens; it is here only because the shape
  // requires it. A declined request issues nothing to either side.
  {
    customer: "usr_karan",
    listing: "lst_modern_apartment",
    quantity: 2,
    daysAgo: 27,
    declinedBecause: "You publish no reliability claim at all, and this is my home for two nights. Send me a proof and I will reconsider.",
    ...noShow,
  },
  {
    customer: "usr_zaid",
    listing: "lst_lakeview_room",
    quantity: 1,
    daysAgo: 14,
    declinedBecause: "Eight bookings not honoured. Happy to hold the room against a deposit instead.",
    ...noShow,
  },
  {
    customer: "usr_vikram",
    listing: "lst_camera_kit",
    quantity: 2,
    daysAgo: 12,
    declinedBecause: "No customer-side history published, and this is a high-value kit.",
    ...noShow,
  },

  // ── Still sitting with the provider, waiting to be decided ──────────────
  { customer: "usr_dev", listing: "lst_cozy_studio", quantity: 2, daysAgo: 0, awaitingDecision: true, ...good },
  { customer: "usr_karan", listing: "lst_garden_flat", quantity: 1, daysAgo: 0, awaitingDecision: true, ...good },
  { customer: "usr_neha", listing: "lst_hot_desk", quantity: 3, daysAgo: 0, awaitingDecision: true, ...good },
];

// ── Past verification requests across the network ──────────────────────────

export interface SeededVerification {
  org: string;
  subject: string;
  text: string;
  /** Days ago. */
  d: number;
  /** Extra hours ago, for ordering several on the same day. */
  h?: number;
  holder: "approve" | "decline" | "pending";
  /** Presenter's note: which demo case this row exists to show. */
  shows?: string;
}

export const SEEDED_VERIFICATIONS: SeededVerification[] = [
  // ── Vineet, the main demo holder ─────────────────────────────────────────
  { org: "org_onecity", subject: "usr_vineet", text: "Has this guest completed at least 5 stays?", d: 41, holder: "decline", shows: "Holder said no — nothing was shared" },
  { org: "org_marketplace_b", subject: "usr_vineet", text: "Does this buyer have at least 10 successful transactions?", d: 36, holder: "approve" },
  { org: "org_onecity", subject: "usr_vineet", text: "Is this guest's booking reliability at least 90%?", d: 30, holder: "approve" },
  { org: "org_marketplace_b", subject: "usr_vineet", text: "Does this seller have at least 25 successful transactions?", d: 26, holder: "approve" },
  { org: "org_marketplace_b", subject: "usr_vineet", text: "Is the seller completion rate at least 95%?", d: 22, holder: "approve" },
  { org: "org_onecity", subject: "usr_vineet", text: "Does this buyer have at least 30 successful bookings?", d: 18, holder: "approve" },
  { org: "org_marketplace_b", subject: "usr_vineet", text: "Does this buyer have at least 15 successful transactions?", d: 14, holder: "approve" },
  { org: "org_onecity", subject: "usr_vineet", text: "Is this guest's booking reliability at least 95%?", d: 10, holder: "approve" },
  { org: "org_marketplace_b", subject: "usr_vineet", text: "Does this seller have at least 40 successful transactions?", d: 6, holder: "approve" },
  { org: "org_marketplace_b", subject: "usr_vineet", text: "Does this buyer have at least 100 successful transactions?", d: 5, holder: "approve", shows: "NOT SATISFIED — the threshold is above his real number" },
  { org: "org_marketplace_b", subject: "usr_vineet", text: "Does this buyer have at least 20 successful bookings?", d: 1, h: 4, holder: "approve" },
  { org: "org_marketplace_b", subject: "usr_vineet", text: "I need to know if this seller has at least 20 successful transactions.", d: 0, holder: "pending", shows: "Waiting for the holder to decide" },

  // ── Requests Cedar refuses outright ──────────────────────────────────────
  { org: "org_marketplace_b", subject: "usr_karan", text: "What is this buyer's phone number and home address?", d: 33, holder: "approve", shows: "BLOCKED — identity details are never disclosable" },
  { org: "org_devhire", subject: "usr_nikhil", text: "Give me this client's complete payment history.", d: 31, holder: "approve", shows: "BLOCKED — full history exceeds minimum disclosure" },
  { org: "org_tripnest", subject: "usr_tanvi", text: "Exactly how many bookings has this guest completed?", d: 27, holder: "approve", shows: "BLOCKED — an exact count is a raw value, not a claim" },
  { org: "org_lendfast", subject: "usr_maya", text: "Does this seller have at least 50 completed orders?", d: 24, holder: "approve", shows: "BLOCKED — LendFast is only registered for buyer checks" },
  { org: "org_datascrape", subject: "usr_rahul", text: "Does this buyer have at least 10 successful transactions?", d: 23, holder: "approve", shows: "BLOCKED — the verifier is not registered with Trustline" },
  { org: "org_marketplace_b", subject: "usr_neha", text: "Send me every order this shopper has ever placed.", d: 20, holder: "approve", shows: "BLOCKED — full history" },
  { org: "org_goride", subject: "usr_aisha", text: "What is this renter's real name and email address?", d: 12, holder: "approve", shows: "BLOCKED — identity" },

  // ── Providers ────────────────────────────────────────────────────────────
  { org: "org_onecity", subject: "usr_arjun", text: "Does this host have at least 100 completed bookings?", d: 34, holder: "approve" },
  { org: "org_onecity", subject: "usr_arjun", text: "Is this host's completion rate at least 95%?", d: 21, holder: "approve" },
  { org: "org_tripnest", subject: "usr_meera", text: "Does this host have at least 50 completed bookings?", d: 29, holder: "approve" },
  { org: "org_onecity", subject: "usr_kabir", text: "Is this host's completion rate at least 90%?", d: 28, holder: "approve" },
  { org: "org_onecity", subject: "usr_ishita", text: "Does this host have at least 10 completed bookings?", d: 15, holder: "approve", shows: "NOT SATISFIED — only two bookings exist" },
  { org: "org_onecity", subject: "usr_devansh", text: "Is this host's completion rate at least 90%?", d: 13, holder: "approve", shows: "NOT SATISFIED — he is at 50%" },
  { org: "org_onecity", subject: "usr_newhost23", text: "Does this host have at least 1 completed booking?", d: 9, holder: "approve", shows: "FAILED — there is no credential at all to prove it from" },
  { org: "org_onecity", subject: "usr_quickstays", text: "Does this host have at least 20 completed bookings?", d: 2, holder: "approve", shows: "FAILED — the credential was revoked by the issuer" },
  { org: "org_drivenow", subject: "usr_priya", text: "Is this car owner's completion rate at least 95%?", d: 26, holder: "approve" },
  { org: "org_drivenow", subject: "usr_vikram", text: "Is this car owner's completion rate at least 90%?", d: 25, holder: "approve", shows: "NOT SATISFIED — he is at 70%" },
  { org: "org_goride", subject: "usr_suresh", text: "Does this driver have at least 500 completed rides?", d: 30, holder: "approve" },
  { org: "org_goride", subject: "usr_imran", text: "Is this driver's completion rate at least 99%?", d: 19, holder: "approve" },
  { org: "org_goride", subject: "usr_manoj", text: "Does this driver have at least 100 completed rides?", d: 8, holder: "approve", shows: "NOT SATISFIED — three rides so far" },
  { org: "org_skyfare", subject: "usr_skybird", text: "Does this airline have at least 10000 flights flown as booked?", d: 22, holder: "approve" },
  { org: "org_skyfare", subject: "usr_fareloop", text: "Is this agent's completion rate at least 90%?", d: 17, holder: "approve", shows: "NOT SATISFIED — 75%" },
  { org: "org_parcelpath", subject: "usr_parcelrun", text: "Does this courier have at least 5000 completed deliveries?", d: 16, holder: "approve" },
  { org: "org_parcelpath", subject: "usr_dashdrop", text: "Is this courier's completion rate at least 80%?", d: 3, holder: "approve", shows: "NOT SATISFIED — 10%" },
  { org: "org_devhire", subject: "usr_sneha", text: "Is this freelancer's completion rate at least 95%?", d: 32, holder: "approve" },
  { org: "org_devhire", subject: "usr_tarun", text: "Is this freelancer's completion rate at least 90%?", d: 11, holder: "decline", shows: "Holder declined rather than fail the check" },
  { org: "org_devhire", subject: "usr_omkar", text: "Does this freelancer have at least 1 delivered project?", d: 7, holder: "approve", shows: "NOT SATISFIED — zero completed out of fourteen" },
  { org: "org_marketplace_b", subject: "usr_rohan", text: "Does this store have at least 50 delivered orders?", d: 18, holder: "approve" },
  { org: "org_onecity", subject: "usr_terracestudio", text: "Is this venue's completion rate at least 90%?", d: 6, holder: "approve", shows: "NOT SATISFIED — one in three events is cancelled" },
  { org: "org_onecity", subject: "usr_naveen", text: "Does this owner have at least 20 completed rentals?", d: 1, h: 6, holder: "approve", shows: "FAILED — the holder withdrew the credential himself" },

  // ── Customers ────────────────────────────────────────────────────────────
  { org: "org_tripnest", subject: "usr_karan", text: "Is this guest's booking reliability at least 80%?", d: 12, holder: "approve", shows: "NOT SATISFIED — he shows up 10% of the time" },
  { org: "org_onecity", subject: "usr_karan", text: "Does this guest have at least 2 successful bookings?", d: 0, holder: "pending" },
  { org: "org_onecity", subject: "usr_ananya", text: "Is this guest's booking reliability at least 90%?", d: 16, holder: "approve" },
  { org: "org_devhire", subject: "usr_nikhil", text: "Is this client's payment reliability at least 90%?", d: 9, holder: "approve", shows: "NOT SATISFIED — half his invoices were late" },
  { org: "org_goride", subject: "usr_rahul", text: "Is this rider's booking reliability at least 95%?", d: 14, holder: "approve" },
  { org: "org_drivenow", subject: "usr_aisha", text: "Is this renter's booking reliability at least 90%?", d: 10, holder: "approve", shows: "NOT SATISFIED — 75%" },
  { org: "org_drivenow", subject: "usr_aisha", text: "Is this renter's booking reliability at least 70%?", d: 0, holder: "pending" },
  { org: "org_onecity", subject: "usr_divya", text: "Does this shopper have at least 3 successful orders?", d: 4, holder: "approve", shows: "NOT SATISFIED — one order so far" },
  { org: "org_skyfare", subject: "usr_zaid", text: "Is this traveller's booking reliability at least 50%?", d: 5, holder: "approve", shows: "NOT SATISFIED — 0%" },
  { org: "org_freshcart", subject: "usr_neha", text: "Does this shopper have at least 500 successful orders?", d: 13, holder: "approve" },
  { org: "org_fixitnow", subject: "usr_gaurav", text: "Is this customer's payment reliability at least 90%?", d: 8, holder: "approve", shows: "NOT SATISFIED — 50%" },
  { org: "org_fixitnow", subject: "usr_gaurav", text: "Is this customer's booking reliability at least 95%?", d: 7, h: 2, holder: "approve", shows: "VERIFIED — he always turns up, he just pays late" },
  { org: "org_tripnest", subject: "usr_tanvi", text: "Does this guest have at least 20 successful bookings?", d: 6, h: 2, holder: "approve", shows: "VERIFIED — she has exactly 20" },
  { org: "org_tripnest", subject: "usr_tanvi", text: "Does this guest have at least 21 successful bookings?", d: 6, h: 1, holder: "approve", shows: "NOT SATISFIED — one short, and the proof is exact" },
  { org: "org_glowbar", subject: "usr_harsh", text: "Does this client have at least 20 successful bookings?", d: 3, h: 3, holder: "approve", shows: "VERIFIED from the live credential, ignoring the revoked one" },
  { org: "org_tablebook", subject: "usr_pooja", text: "Does this diner have at least 40 honoured reservations?", d: 2, h: 5, holder: "approve", shows: "VERIFIED, but from a record nearly three years old" },
  { org: "org_deskhub", subject: "usr_faiz", text: "Does this member have at least 500 successful bookings?", d: 4, h: 6, holder: "approve" },
  { org: "org_pawpals", subject: "usr_shreya", text: "Is this customer's booking reliability at least 95%?", d: 5, h: 4, holder: "approve" },
  { org: "org_marketplace_b", subject: "usr_maya", text: "Is the seller completion rate at least 90%?", d: 9, h: 5, holder: "approve" },
  { org: "org_marketplace_b", subject: "usr_maya", text: "Is this buyer's booking reliability at least 95%?", d: 9, h: 3, holder: "approve" },
  { org: "org_onecity", subject: "usr_dev", text: "Does this traveller have at least 1 successful booking?", d: 2, h: 2, holder: "approve", shows: "FAILED — a brand-new holder with no credentials" },
  { org: "org_onecity", subject: "usr_dev", text: "Is this traveller's booking reliability at least 80%?", d: 0, h: 6, holder: "pending" },
  { org: "org_tripnest", subject: "usr_pooja", text: "Is this diner's booking reliability at least 90%?", d: 0, h: 3, holder: "pending" },
];
